### ISSUE TITLE
Pesquisar e implementar os botões via webchat

### ISSUE THREAD

**Issue by ricardopoppi** [defensoriapublicasp/bot#16]
Estudar sobre os botões e subir o bot com o webchat.

**Tarefas:**
- [x] Subir o bot com o webchat
- [x] Pesquisar e implementar botões

**Criterios de Aceitação:**
- [x] Página com o bot via webchat implementada
- [x] Um exemplo de botão feito

**Comment by gabibguedes** [comment]
Webchat está na página index.html na raiz do repositório.
Para roda-lo execute o comando: 
``` sh
docker-compose up bot
``` 
e abra o `index.html` em seu navegador

**Comment by gabibguedes** [comment]
Para fazer um botão siga o template de utter abaixo:
``` yml
 utter_nome_da_utter:
    - text: Texto da utter para resposta do bot
      buttons:
      - title: Titulo do botão 1
        payload: resposta que será recebida pelo bot
      - title: Titulo do botão 2
        payload: outra resposta que será recebida pelo bot
```

**ATENÇÃO:** Não utilize o pipe "|" para escrever o texto da utter, ele torna o botão parte do texto de resposta da utter.

Veja o exemplo:

``` yml
 utter_civel:
    - text: Primeiro vamos identificar se estamos falando de uma propositura ou de uma defesa... Você nos procurou pois recebeu uma carta do Poder Judiciário?
      buttons:
      - title: sim
        payload: sim
      - title: não
        payload: não
```
